version: "3.9"

volumes:
  redis_data:
  app_files:

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    restart: always
    build: .
    ports:
      - "8092:8092"
    depends_on:
      - redis
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      JAVA_OPTS: '-Xmx512m'

      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      OPEN_AI_TOKEN: ${OPEN_AI_TOKEN}
      NOTION_API_TOKEN: ${NOTION_API_TOKEN}
      NGROK_URL: ${NGROK_URL}
    volumes:
      - app_files:/app/files
